version: "3.9"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:11.0.3
    container_name: keycloak-11
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    volumes:
      - ./keycloak_data:/opt/jboss/keycloak/standalone/data
    restart: unless-stopped
