name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    name: Build and Deploy Job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --ignore-scripts

      # Optional – wenn flaky, zunächst deaktivieren oder continue-on-error: true
      - name: Run unit tests
        run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessNoSandbox
        continue-on-error: true

      # Kein eigener Build nötig – die SWA Action baut
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DANIEL_STUDENT }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: "/"                        # Root deines Angular-Projekts
          api_location: ""                         # falls keine API
          output_location: "dist/angular-blog-app-daniel-wuester/browser"  # Angular 17+: /browser

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DANIEL_STUDENT }}
          action: close
          app_location: "/"

  dependabot_test:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    name: Test Dependabot PR
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci --ignore-scripts
      - run: npm test
