name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  pr_build:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    name: PR Build & Test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Run unit tests
        run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessNoSandbox

  deploy_main:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Deploy to Azure Static Web Apps
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Run unit tests (non-blocking)
        run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessNoSandbox
        continue-on-error: true

      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DANIEL_STUDENT }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: "/"                                   # Root des Angular-Projekts
          api_location: ""                                    # keine API
          output_location: "dist/angular-blog-app-daniel-wuester/browser"  # Angular 17+: /browser
